### ISSUE TITLE
parameter set issue

### ISSUE THREAD

**Issue by Rahulsurve45** [wetcon/OPCUA4PACTware#39]
We are able to able to see all values of the HART enabled device in Pactware such as process values, device details etc. In Matrikon, through the wetcon OPC UA plugin, we are only able to see the details such as model no., device id, device make etc. We are not able to see the process values of the device in Matrikon.

**Comment by jjell** [comment]
Hi Rahulsurve45,

it can be possible that your device DTM does not expose the process variables via IDtmParameter.GetParameters() FDT mechanism. You needed to ask the device manufacturer about that.

Kind regards,
Jonas
