### ISSUE TITLE
Application example

### ISSUE THREAD

**Issue by Alex13Dev** [wetcon/OPCUA4PACTware#4]
Hello!
Where can I see an example of using OPCUA4PACTware for reading / writing this device? I am trying to read data from the device, but I do not understand how. The TransferFromDevice, TransferToDevice, FetchTransferResultData methods have AccessLevel = Read (this is how UA UaExpert shows).

**Comment by jjell** [comment]
Hello Alex,
using UaExpert client you can invoke such a method by right clicking the item within the "Transfer" node and clicking on "Call...". 
The FetchTransferResultData method can only be called after a TransferFromDevice or TransferToDevice invocation using the returned TransferId output parameter.
![uaexpert](https://user-images.githubusercontent.com/52195775/112279138-db226180-8c83-11eb-8bbc-6ef82bd25c69.jpg)

**Comment by gobikulandaisamy** [comment]
![image](https://user-images.githubusercontent.com/24189431/115613660-51a99200-a30a-11eb-932e-03f5fa5268b1.png)

Sir 

1. We added Device DTM in Pactware 5.X . 
2. Then we clicked Online Parameter, then the Device Details shown in Pactware,
3. Then I used UAExpert and browse the Particular Device from Device set and browed Parameter Node.
4. But Parameter Node  is not showing the Parameters.
5. Please see the above picture.
6. Kindly guide me.
